---
## Configure header of page
text_align_right: false
show_title_as_headline: false
format: hugo-md
headline: Bastián Olea Herrera
---

Blog de Bastián Olea Herrera [(@bastimapache)](https://x.com/bastimapache), Sociólogo (UAH) y Magíster en Sociología (PUC). Dedicado profesionalmente a la ciencia de datos, particularmente su aplicación a temáticas sociales y socioeconómicas.

```{r}
#| echo: false
#| message: false

library(shiny)
library(htmltools)
```


```{r texto_morado}
#| echo: false

cuadro <- div(
  style = css(padding = "16px", padding_bottom = "1px", padding_top = "1px", 
              background_color = "#493365", color = "#E9DDEE",
              border_radius = "6px",
              margin = "20px", margin_top = "40px", margin_left = "30px", margin_right = "30px",
              font_size = "90%"),
  markdown("¿Quieres **aprender R**, desarrollar apps con R, o tienes un proyecto en mente? [¡Contáctame!](/contact/) Ofrezco clases particulares de R, asesorías, desarrollo de apps, y apoyo para cualquier tipo de proyecto.")
)

return(cuadro)
```


